name = "fourteen45-theme"
description = "The theme for the fourteen45 website"
license = "MIT"
source_repo = "https://github.com/sheenobu/fourteen45-theme"
tags = ["blog", "purecss"]

[author]
    name = "sheenobu"
    twitter = "http://twitter.com/sheenobu"
    url = "http://github.com/sheenobu"
